### ISSUE TITLE
Question:  How is this different from KeySubtracter with KeyHunt?

### ISSUE THREAD

**Issue by coolj-9480** [bakd247/ecdsaKeyFinder#10]
[KeySubtracter](https://github.com/albertobsd/keysubtracter) is used to generate multiple public keys from a known public key. Using [KeyHunt](https://github.com/albertobsd/keyhunt) you can search for the private key against the list of keys to find the private key of the original, at an average of 1 million keys per second per thread.

Am I wrong or is your strategy similar? I ask because the above method is brute force and you wrote "using this method are 100% greater than using both brute force as well as just plain NOT attempting at all..".

**Comment by bakd247** [comment]
I have never heard of "keyhunt"...
I developed this myself....hashAdder is the better version I am working on which uses much more than just a basic list.....

**Comment by bakd247** [comment]
this method is far superior to brute force because it searches for multiples of a key as well as the key itself...so it is looking for as many keys as you tell it to look for that all correspond to the same key....
please read the description in its entirety before commenting with an "issue"
