### ISSUE TITLE
invalid literal for int() with base 16

### ISSUE THREAD

**Issue by greenpp88** [bakd247/ecdsaKeyFinder#12]
Hi

I am running on  python 3.11 and here is the result

Traceback (most recent call last):
  File "C:\ecdsaKeyFinder\privateKeyFinder.py", line 6, in <module>
    X = int((input("cf62ff81cc183xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")),16)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: ''

what's wrong?

Thanks

**Comment by greenpp88** [comment]
how to fix it

**Comment by bakd247** [comment]
You may need to use a later version of python...or update your current packages
is that an exact copy of the output?
i have never seen that error before...and it seems to work fine for me...
it looks like a memory error...
its supposed to be a random 16 byte integer (256 bits) which always results in a hex output....if it returned all those x's then your "random" package may be outdated or something like that....
are you running it in its own environment? be sure not to run it in visual studio code terminal...

if you navigate to the folder and run the file directly from your command line using "python3 ecdsaKeyFinder.py" then you should not have any memory errors

I will double check that all the files are correct and in order but I have done extensive testing on this so I hope this helps....please let me know....thanks

**Comment by bakd247** [comment]
oh wait...now I see whats going on...your not entering the public key correctly...
make sure you are entering the correct x coordinate for the pubic key in hex format
do NOT include the 02, 03 or 04 at the start of the public key...example
public key x coordinate is 025b75fd5f49e78191a45e1c9438644fe5d065ea98920c63e9eef86e151e99b809
then you would enter 5b75fd5f49e78191a45e1c9438644fe5d065ea98920c63e9eef86e151e99b809
and the same for the y coordinate

**Comment by greenpp88** [comment]
Hello

Thanks for the reply

I did put the x coordinate
which is "cf62ff81cc183xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" - mention in the output. 

To answer your questions:

"it looks like a memory error..."
what is the min ram GB to run this code?

I am running on windows cmd 

I will try to install python 3.12 and see what's happen

**Comment by greenpp88** [comment]
Hello

I still using python 3.11

![Screenshot_1](https://github.com/bakd247/ecdsaKeyFinder/assets/166028431/d798c0d0-0dc9-4e89-adf6-f29a595c43d6)
This is when i start the program 

after it shown the x coordinate then I press "enter tab"
![Screenshot_2](https://github.com/bakd247/ecdsaKeyFinder/assets/166028431/1f728aca-5f20-4ead-ae3e-edc1eec4c600)

the error appear on the screen.

am i doing wrong by pressing the "enter"?
