### ISSUE TITLE
hashlib error 

### ISSUE THREAD

**Issue by mikejnpc** [bakd247/ecdsaKeyFinder#3]
Creating Collision List...Please Wait...
Multiples Collision List Created...
Please Enter the Size of the Halves Collision List you would like to Create. Best Performance around 100,000:100000
Halves Collision List Created...
Searching For Key...Please Wait...
164.0  keys per second
Total Positions Tried: 10000
Traceback (most recent call last):
  File "privatekeyfinder.py", line 136, in <module>
    privKey = int((hashlib.sha256(os.urandom(16)).hexdigest()), 16)
NameError: name 'hashlib' is not defined

wrong lib or error in the script ?

**Comment by bakd247** [comment]
I fixed this error...sorry about that....I forgot to delete one line of code when I made the update yesterday...
it is fixed now and everything works as it should without hashlib
