### ISSUE TITLE
ecdsakeyfinder

### ISSUE THREAD

**Issue by moedacompix** [bakd247/ecdsaKeyFinder#4]
privateKeyFinder.py", line 67
    elif BB.x != PublicKey.x:
    ^^^^
SyntaxError: invalid syntax

**Comment by bakd247** [comment]
Im sorry…that you had that happen…I actually fixed this a few minutes ago…just before I saw your message…you must have literally just downloaded it while I was fixing it...
talk about odd timing…that line of code was only like that for about 3 minutes…lol
again sorry….It is fixed now…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: Monday, April 17, 2023 5:58 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [bakd247/ecdsaKeyFinder] ecdsakeyfinder (Issue #4)


privateKeyFinder.py", line 67
elif BB.x != PublicKey.x:
^^^^
SyntaxError: invalid syntax
