### ISSUE TITLE
How to check

### ISSUE THREAD

**Issue by sssergy** [bakd247/ecdsaKeyFinder#7]
And how can I check the operation of this script, whether it works or not?

**Comment by bakd247** [comment]
I just provided an updated version...
you can run it by just inputting a public key that you already know the private key to and see that it find it  by finding one of the multiples....
you can try it with any key like this:   private key*(multiple) mod (n)
then plug that private key into pycoin or any ecdsa Module and get the public key...
now run the program with the public key you want it to find and it will find the private key for that public key....

I will be making a video showing this very soon.....
it just took me about 6 months to figure out how to get the new multiplication mechanism working to allow for a much faster hashrate per operation

updates coming this week

**Comment by bakd247** [comment]
fyi...run the privateKeyFinder.py code that I uploaded today... not the older version...the newest one guaranteed works like a charm in every direction

**Comment by bakd247** [comment]
Updates and how to video coming this week and later this month
